[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "my-cowsay"
version = "1.0"
dependencies = [
  "cowsay",
]

[project.optional-dependencies]
test = ["pytest"]

[tool.ruff.format]
quote-style = "single"
